<html>
<head>
<title>Python Exception Handling</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Python异常处理</h1>
<blockquote>原文：<a href="https://blog.devgenius.io/python-exception-handling-bbaea543785b?source=collection_archive---------10-----------------------#2020-09-17">https://blog.devgenius.io/python-exception-handling-bbaea543785b?source=collection_archive---------10-----------------------#2020-09-17</a></blockquote><div><div class="fc ib ic id ie if"/><div class="ig ih ii ij ik"><div class=""/><h1 id="39e5" class="jk jl in bd jm jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh bi translated">概观</h1><p id="d40b" class="pw-post-body-paragraph ki kj in kk b kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld le lf ig bi translated">在编程中有错误和例外。错误是程序不能处理的问题，但异常可以。错误的例子有语法错误、内存不足错误和递归错误。异常是在程序运行时检测到并可以处理的错误。错误处理的主要模块是try、except、else和finally。</p><h1 id="d809" class="jk jl in bd jm jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh bi translated">尝试</h1><p id="dcee" class="pw-post-body-paragraph ki kj in kk b kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld le lf ig bi translated">在try块中，您将代码放在您认为会发生异常的地方。如果没有异常，那么将运行try块中的整个代码，并跳过except块。如果try块中出现异常，则跳过剩余的代码。</p><pre class="lg lh li lj gt lk ll lm ln aw lo bi"><span id="5f24" class="lp jl in ll b gy lq lr l ls lt"><strong class="ll io">try</strong>:<br/>    x = int(input("Please enter a number: "))</span></pre><h1 id="6437" class="jk jl in bd jm jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh bi translated">除...之外</h1><p id="2c87" class="pw-post-body-paragraph ki kj in kk b kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld le lf ig bi translated">except块是定义预期发生的异常的地方。如果except块不处理特定的异常，它将尝试将异常传递给外部try块。如果该异常未被处理，则它是一个未处理的异常，程序会停止并打印一条异常消息。</p><pre class="lg lh li lj gt lk ll lm ln aw lo bi"><span id="6eeb" class="lp jl in ll b gy lq lr l ls lt">try:<br/>    x = int(input("Please enter a number: "))<br/>except ValueError:<br/>    print("Oops!  That was no valid number.  Try again...")</span></pre><h1 id="96de" class="jk jl in bd jm jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh bi translated">其他</h1><p id="5752" class="pw-post-body-paragraph ki kj in kk b kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld le lf ig bi translated">else块是没有异常时执行代码的地方。可以在一个块中处理多个异常。</p><pre class="lg lh li lj gt lk ll lm ln aw lo bi"><span id="4fbd" class="lp jl in ll b gy lq lr l ls lt">try:<br/>    x = int(input("Please enter a number: "))<br/>except ValueError:<br/>    print("Oops!  That was no valid number.  Try again...")<br/>else:<br/>    print("Valid number")</span></pre><h1 id="8ef5" class="jk jl in bd jm jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh bi translated">最后</h1><p id="667d" class="pw-post-body-paragraph ki kj in kk b kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld le lf ig bi translated">finally块是不管是否有异常都要执行的代码。如果有一个异常没有被处理，那么在异常被传递之前，finally块首先被执行。如果在错误处理中有中断、继续或返回，那么finally代码块就在它们之前执行。如果finally有return语句，那么finally块将是返回值，而不是其他块。</p><pre class="lg lh li lj gt lk ll lm ln aw lo bi"><span id="1276" class="lp jl in ll b gy lq lr l ls lt">try:<br/>    x = int(input("Please enter a number: "))<br/>except ValueError:<br/>    print("Oops!  That was no valid number.  Try again...")<br/>else:<br/>    print("Valid number")<br/>finally:<br/>    print("Always executed")</span></pre><h1 id="c215" class="jk jl in bd jm jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh bi translated">结论</h1><p id="b136" class="pw-post-body-paragraph ki kj in kk b kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld le lf ig bi translated">当您的项目正在开发中时，您希望避免任何中断。为了避免这些中断，你应该尝试自己处理错误，而不是让程序暂停。在尝试处理异常时，您可以使用父异常类来处理更一般的异常，也可以使用特定的类来处理某些异常。也可以创建自己的异常并处理它。</p></div></div>    
</body>
</html>