# 在 Java 中处理异常的 5 个最佳实践

> 原文：<https://blog.devgenius.io/5-best-practices-to-handle-exceptions-in-java-5e1534f83772?source=collection_archive---------4----------------------->

## 软件工程之旅- JAVA

## 在 Java 中处理异常的 5 个最佳实践

![](img/9edafbb5e300ca92b228f79d08a1b42a.png)

[照片由 Ayelt van Veen 在 Unsplash 上拍摄](https://unsplash.com/@ayeltvanveen)

# 概观

异常是在应用程序执行过程中发生的不想要的或意外的事件。异常，由程序员或软件工程师处理。Java 中的异常处理是处理运行时错误的强大机制之一，因此可以维护应用程序的正常流程，而不会出现任何问题。异常发生的原因有很多，但我可以尝试列出一些常见的运行时错误:

*   无效的用户输入
*   由于缺少边缘情况而导致的代码错误
*   网络接线
*   被遗忘

在本文中，我将介绍一些对您有帮助的最佳实践，并给出一些示例，这些示例可以让您更多地了解异常并将其应用到您的项目中。

# #1 使用 Finally 或使用 Try With Resource 语句清理资源

在 Java 中，当你在你的 try 块中使用一个资源时，比如一个 InputStream，你需要在之后关闭它。在这些情况下，一个常见的错误是在 try 块的末尾关闭资源。

在 try 块出现异常之前，一切都会很好。那么您的资源就不能关闭，因为您的代码不能到达 try 块的末尾。为此，我们应该应用下面两种方法来使我们的资源在任何情况下都可以关闭代码。

## 用 Finally 清理资源

对于下面的例子，我们使用 finally 块来关闭我们的资源。如你所见，如果我们的代码发生了任何情况，代码总是进入 finally 块，这使得我们的资源总是像预期的那样关闭。例如，您可以参考示例代码:

用 Finally 示例清理资源

## 通过 Try With Resource 语句清理资源

使我们的资源按预期关闭的其他方法是使用 Try With Resource 语句，如下面的代码所示。以这种方式使用时，我们的代码更少，但您的资源必须实现“自动关闭”接口。大多数 Java 标准资源都是这么做的。例如:

通过 Try-With-Resource 语句清理资源示例

# #2 处理多个异常

在处理异常时，您可能经常面临的一个问题是如何处理 try 块的多个异常。下面这些例子可以帮助你更清楚如何得到适合你的东西。

## 运算符“|”的多个异常

您可以在下面的示例中看到，我在 catch 块中使用了运算符“|”来捕捉两个异常(“ArithmeticException”和“ArrayIndexOutOfBoundsException”)。这样，万一两个异常中的任何一个发生，我都可以得到我想要的结果。

你也可以使用父异常来捕捉而不是使用多个异常，但是这种方式可能会让你不清楚你会发生什么异常。例如:

运算符“|”的多个异常示例

## 带有多个 Catch 块的多个异常

与用运算符“|”捕获多个异常不同，在这个例子中，我对异常使用了多个捕获。这可能会使我的代码更长，但是根据我得到的结果，正如你在例子中看到的，我可以确定我的代码发生了什么异常。例如:

具有多个 Catch 块的多个异常示例

# #3 记录并丢弃

log 和 throw 有区别也有相似之处。参见下面的例子，可以更清楚地了解什么时候应该使用 log，什么时候应该使用 throw。

## 用日志处理异常

下面的例子向我们展示了如何在 catch 块中使用 log。每当我们使用日志时，我们都可以在应用程序日志中获得关于异常的信息，而不会终止。当您希望您的应用程序运行时，尽管您知道会发生异常，但只想忽略这些异常以继续其他正常进程时，通常会使用这种方法。例如:

用日志示例处理异常

您可以看到下面的输出:

使用日志示例处理异常的输出

# 用 Throw 处理异常

有时我们不接受一些可以通过 try catch 块传递的异常。这是因为例外可能是关键问题或重要的业务不应该错过。在这种情况下，我们应该像下面的例子那样使用 throw 让应用程序被异常终止。例如:

使用抛出示例处理异常

代码的输出:

带有抛出示例的句柄异常的输出

# #4 Finally 块和返回语句

try 块中带有 return 语句的 finally 块有一个特例。下面的例子将向你展示这是如何工作的。

正如您在代码中看到的，您可以获取并运行代码，然后您可能会看到代码的结果是“1”而不是“0”。这是因为当我们在 try 块中有一个 return 语句并且在 try 之后有一个 finally 块时，在执行 return 语句之前，代码应该首先执行 finally 中的所有代码。所以这里的第一个 return 语句是“return 1”，而不是“0”。

例如:

Finally 块和返回语句示例

# 使用 Finally Block 的 5 个技巧

我想展示的与异常主题相关的最后一件事是使用 finally 块时的提示，您可以在实际情况中应用或避免这些提示。

## 不使用 Catch 块传递异常

在某些情况下，我们可能会放置一个 try 块来传递一些我们认为代码可能会发生的未知异常。有时我们只需要传递，而 catch 块中没有我们想要实现的东西。在这种情况下，我们可以跳过 catch 块，只使用 try with finally，如下例所示:

传递异常，但不传递 Catch 块示例

## 不应在 Finally 块中引发任何异常

实际上，我们可以在任何我们想编码的地方编码。这个例子并不完全要求你继续下去。这只是一个小小的警告，当您使用 throw with finally 块时，可能会使您无法获得原来的异常。相反，您只会看到您在 finally 块中抛出的异常。例如:

不建议对 Finally 块示例使用 Throw

# 结论

在本文中，我们探讨了 Java 异常处理的一些最佳实践。尽管决定使用哪种方法有许多因素，但本文中分享的最佳实践应该为您提供一个很好的切入点，以便您进行更多的探索或将其应用到您未来的 Java 项目中。我希望这些最佳实践对您有所帮助。

*喜欢这篇文章？给我弄个* [*Ko-fi*](https://ko-fi.com/techisbeautiful) *。*

*爱我的文字？加入我的* [*邮箱列表*](https://medium.com/subscribe/@techisbeautiful) *。*

*爱读书？加入*[*Medium*](https://medium.com/@techisbeautiful/membership)*(如果你用上面的链接，也是支持我，因为我有 Medium 的小提成)。*

如果你喜欢这个故事，你也会喜欢:

*   [你必须知道的 Java 18: 4 特性](/java-18-top-4-features-you-must-know-1f36ee23e2ab)
*   [你必须知道的 Java 17: 5 特性](https://medium.com/@techisbeautiful/java-17-top-5-features-you-must-know-bbed2afaea3d)
*   [你必须知道的 Java 11: 8 特性](https://medium.com/@techisbeautiful/new-features-you-must-know-in-java-11-and-examples-3fda2ad26def)
*   [你必须知道的 Java 8 : 7 特性](/java-8-seven-features-you-must-know-and-examples-1c3964ae7fe8)